# Generated by Django 5.0 on 2024-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_created_date_alter_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram_id'),
        ),
    ]
