# Generated by Django 5.0 on 2024-12-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Username')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram_id')),
                ('balance', models.BigIntegerField(blank=True, null=True, verbose_name='Umummiy Balance')),
                ('summa', models.BigIntegerField(blank=True, null=True, verbose_name='Tolov Miqtori')),
                ('number', models.BigIntegerField(blank=True, null=True, verbose_name='Telefon raqami')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklash')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana"),
        ),
    ]
