# Generated by Django 5.0 on 2024-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_author_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='univer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Universitet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Muallif'),
        ),
    ]
