# Generated by Django 5.0 on 2024-12-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mualif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('uzb', 'Uzbek'), ('rus', 'Russian')], default='eng', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='univer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universitet'),
        ),
    ]
