# Generated by Django 5.0 on 2024-12-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_author_alter_user_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Fullname'),
            preserve_default=False,
        ),
    ]
