# Generated by Django 5.0 on 2024-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_payment_is_blocked_remove_payment_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.BigIntegerField(default=1, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='summa',
            field=models.BigIntegerField(default=1, verbose_name='Tolov Miqtori'),
            preserve_default=False,
        ),
    ]
