# Generated by Django 5.0 on 2025-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_payment_file_id_alter_payment_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_list', models.JSONField(default=list)),
            ],
        ),
    ]
