# Generated by Django 5.0 on 2024-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_created_date_user_is_blocked_user_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Blocklash'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register',
            field=models.BooleanField(default=False, verbose_name='Register'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sanaa"),
        ),
    ]
