# Generated by Django 5.0 on 2024-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_payment_delete_promocode_alter_user_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.CharField(default='', max_length=250, verbose_name='Muallif'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=3),
        ),
    ]
