# Generated by Django 5.0 on 2024-12-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_univer_alter_user_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=3, null=True),
        ),
    ]
