# Generated by Django 5.0 on 2024-12-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_payment_number_alter_payment_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.CharField(default='', max_length=100, verbose_name='Invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.BigIntegerField(verbose_name='Telegram_id'),
        ),
    ]
