# Generated by Django 5.0 on 2024-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_payment_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='file_id',
            field=models.CharField(max_length=500, verbose_name='Chek_id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.CharField(max_length=100, unique=True, verbose_name='Invoice'),
        ),
    ]
