# Generated by Django 5.0 on 2025-01-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_channelrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelRequest',
        ),
    ]
