# Generated by Django 5.0 on 2025-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_promocode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Message ID'),
        ),
    ]
